In [1]:
import torch

In [28]:
import numpy as np
import time 

In [3]:
x = torch.tensor([[1.0 , 4.0 , 7.0] , [2.0 , 3.0 , 6.0]])
x

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [4]:
x.shape , x.dtype


(torch.Size([2, 3]), torch.float32)

In [5]:
x[0,1]

tensor(4.)

In [6]:
x[: , 1]

tensor([4., 3.])

In [7]:
#addition itemwise
10 * (x + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [8]:
#itemwise exp
x.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [9]:
#mean
x.mean()

tensor(3.8333)

In [10]:
x.max(dim=0) #max value per column i.e. dim 0

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [11]:
#lin alg 
#matrix transpose and matrix multiplication 

x @ x.T

tensor([[66., 56.],
        [56., 49.]])

In [12]:
#can change tensors to numpy array

x.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [13]:
torch.tensor(np.array([[1. , 4. , 7.] , [2. , 3. , 6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [14]:
#better to use float32

torch.tensor(np.array([[1. , 4. , 7.] , [2. , 3. , 6.]]) , dtype=torch.float32)

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [15]:
#can use floattensor which auto use float32

torch.FloatTensor(np.array([[1. , 4. , 7.] , [2. , 3. , 6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [16]:
x[: , 1] = -99

In [17]:
x

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [18]:
x.relu_() #uses relu function

tensor([[1., 0., 7.],
        [2., 0., 6.]])

<h3><b><u>Hardware acceleration

In [19]:
if torch.cuda.is_available():
    device="cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [20]:
device

'cuda'

In [21]:
m = torch.tensor([[1. , 4. , 7.] , [2. , 3. , 6.]]) #create tensor on cpu then copy it to gpu
m = m.to(device)

In [22]:
m.device

device(type='cuda', index=0)

In [23]:
#create tensor directly on gpu using device argument

m = torch.tensor([[1. , 4. , 7.] , [2. , 3. , 6.]] , device=device)

In [24]:
r = m @ m.T #ran on gpu
r

tensor([[66., 56.],
        [56., 49.]], device='cuda:0')

In [25]:
m_ = torch.rand((1000 , 1000))
%timeit m_ @ m_.T

6.02 ms ± 76.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
# m = torch.rand((100 , 100) , device="cuda")
# torch.cuda.synchronize()

In [27]:
m_yeah = torch.rand((1000 , 1000) , device="cuda")
%timeit m_yeah @ m_yeah.T

509 μs ± 12.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
