In [2]:
import numpy as np

In [6]:
np_array_one = np.array([1,2,3,4,5])
np_array_two = np.array([6,7,8,9,10])

np_combined = np.c_[np_array_two , np_array_one]
np_yeah = np_array_two + np_array_one

np_combined , np_yeah

(array([[ 6,  1],
        [ 7,  2],
        [ 8,  3],
        [ 9,  4],
        [10,  5]]),
 array([ 7,  9, 11, 13, 15]))

In [ ]:
print(np_array_one[0:5:2])

[1 3 5]


In [ ]:
list_ = list(np_array_one)

print(list[0:5:2])

#fuck this shit am out no thanks 

TypeError: 'list' object is not callable

In [14]:
np_array_one.shape

(5,)

In [15]:
np_array_one.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [16]:
np_array_one.shape

(5,)